<!DOCTYPE html>
<html lang="en">
<head>
	<title>NEC EMS FAQ</title>
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<link rel="stylesheet" href="../css/MyStyleSheet.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<link href="../css/half-slider.css" rel="stylesheet">
	<link href="../css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="../css/necui.css" rel="stylesheet" />
</head>

<%@page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1" session="true"%>

<!-- Login Credential Part -->
<%
if (request.getParameter("psw") != null) {
	String password = request.getParameter("psw");
	String username = request.getParameter("uname");
	session.setAttribute("password", password);
	session.setAttribute("username", username);
}
String pass = null;
if (session.getAttribute("password") != null)
	pass = (String) session.getAttribute("password");	
if (pass == null)
	pass = "";
if (!pass.equals("nec12345")) {
%>

<body>
	<font size="4">Incorrect Password!! </font> <br> <br>
	<font size="4">Back to </font>
	<button type="button" onclick="location.href='../LoginForm.jsp'">
		<font size="3">EMS Login Page</font>
	</button>
</body>

<%	return; 
}	%>
<!---------- Login Credential End ---------->


<%	//OperationsEngineMainModule oem = OperationsEngineMainModule.getInstance();	%>

<script>
   var username = '<%= (String) session.getAttribute("username") %>';
   var password = '<%= (String) session.getAttribute("password") %>';
   var ipAddress = '{{ ipAddress }}';
</script>

<body>
	<!--header information-->
	<div class="container" id="navmain">
    	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        	<div class="container-fluid">
            	<div class="navbar-header">
            		<a class="navbar-brand active" href="/EMSOperationsEngine/LoginForm.jsp"><i class="fa fa-plug"></i> NEC EMS BTM Application</a>
            	</div>
            	<!-- Insert loggedinnavbar.jsp -->
            	<ul class="nav navbar-nav" style="float: none !Important;">
					<li><a href="NECEMS_Main.jsp"><font size="4"><span class="glyphicon glyphicon-cog"></span>Input</font></a></li>
					<li><a href="SizingAnalysis.jsp"><font size="4"><span class="fa fa-database"></span>Sizing Analysis</font></a></li>
					<li><a href="LogPage.jsp"><font size="4"><span class="fa fa-bar-chart"></span>Output</font></a></li>
					<li><a href="FAQ.jsp"><font size="4" color="white"><i class="fa fa-question-circle"></i>FAQ</font></a></li>
					<li style="float: right; margin-right: 5%"><a href="/EMSOperationsEngine/LoginForm.jsp"><font size="4"><span class="glyphicon glyphicon-home"></span> Logout</font></a></li>
				</ul>
        	</div>
    	</nav>
	</div>
	
	<br><br><br><br>

	<div class="container"  id="parentTab"  style="width:90%; ">
		<h3>Questions Related to <b>Input</b> Page</h3>
		<ul>
		<dl>
			<dt>
				How can I run the simulation?
			</dt>
			<dd>
				In order to run EMS simulation, you need to pick up at least one battery size, one tariff, and one load from the lists on the "Input" page, and then click RUN button.
				You will be able to keep track of the simulation progress in the "EMS Simulation Status Log" section.
				After the simulation(s), you can see the results and analysis on "Output" page.
			</dd>
			<br>
			<dt>
				How can I see the content of load and tariff files?
			</dt>
			<dd>
				All the load and tariff data in your account can be downloaded from the selection menus of "Optional: Download Load or Tariff" section.
				You can also check load and tariff data after the simulation in "Output" page or in annual report that can be generated by clicking "Generate Annual Report".
			</dd>
			<br>
			<dt>
				How should I deal with daylight savings time when importing new load data?
			</dt>
			<dd>
				The BTM tool always checks the number of data in new load data depending on being leap year or not. 
				If the data length is not correct the system does not accept the load data. 
				In order to cope with daylight savings time, you could delete one of the data with the same time stamp. 
				However, just make sure that at the end of daylight saving time, you need to add a missing data as the time stamp will typically skip from 1 am to 3 am.
			</dd>
			<br>		
			<dt>
				What if a load data set begins in the middle of a month (EX. on May 17th) and runs one year.
				Will the system start assuming that the data starts from beginning of the month? (EX. from May 1, not May 17th?)
				<!-- Should I maybe fake data from the beginning of the month, start on the next month, etc. -->
			</dt>
			<dd>
				Yes, the system comprehend the newly imported data starting from the beginning of the month.
				You could probably fake some data from the beginning of the month, and cut out the extra data at the end. 
				Or you may cut out the data to make it start from the beginning of next month, and make up with fake data at the end.
			</dd>
			<br>
			<dt>
				I was able to upload the inputs (load & tariffs) and run the simulation without any errors.
				However, the monthly summary reports generated were blank. 
				<!--  I made couple of attempts with different system configurations and got the same error. -->
				Can someone please help figure out how to fix this issue?
			</dt>
			<dd>
				This type of problem was typically related to wrong naming of the tariff/load to be imported.
				We do not recommend to use any space or special characters such as ", . / { * ^ $" as EMS will be confused with those characters and cause path issues.
			</dd>
			<br>
			<dt>
				What is the definition of "PV Scaling Factor" when I want to use PV?
			</dt>
			<dd>
				The scaling factor is usually used for normalized PV profile, which means all the data are divided by the maximum PV value of an entire year so that the whole PV profile ranges from 0 to 1.
				By the scaling factor you input, all the data of PV will be multiplied by the value.
				For instance, if you input 400 as scaling factor, each element of the PV profile is multiplied by 400.
				Because we have fewer profiles for PV, sometimes normalized PV profiles (both necla and sce profiles on UI are normalized) are used to match the load to see the impact of PV integration. 
				If you want to use the PV data as it is (not normalized), you do not have to care about the scaling factor.	
			</dd>
			<br>
			<dt>
				What is the "Import New PV Data with PVWatts" function?
			</dt>
			<dd>
				This function uses the API provided by NREL to import annual PV data with hourly interval. 
				You can just specify the latitude and longitude with nominal capacity of PV to import PV data for that location. 
			</dd>
		</dl>
      </ul>
      
      <h3>Questions Related to <b>Sizing Analysis</b> Page</h3>
      <ul>
		<dl>
			<dt>
				What does the color of the circles mean? 
			</dt>
			<dd>
				The color of the circle represents payback period. If it is green, that battery has better payback period over the ones with red color.
			</dd>
			<br>
			<dt>
				Can you rotate the 3D chart? 
			</dt>
			<dd>
				Yes, just left click and rotate the chart to see it from various angles.
			</dd>
			<br>
			<dt>
				What happens if you delete scenario? 
			</dt>
			<dd>
				"Delete Scenario" removes all the results related to the scenario (combination of load, tariff, and PV). Therefore, if you have run the simulations for multiple battery sizes with the same scenario, it removes all those results.
			</dd>
		</dl>
	</ul>
      
      <h3>Questions Related to <b>Output</b> Page</h3>
      <ul>
		<dl>
			<dt>
				On Summary page, what does "Basecase" mean? In particular, is the Basecase of "Annual Excess PV Generation and Utilization" what PV produces regardless of ESS?
			</dt>
			<dd>
				"Basecase" is the case without using Battery whereas "EMS" is labeled if Battery is used.
				The value of Basecase of "Annual Excess PV Generation and Utilization" is not exactly what PV produces without ESS.
				We first calculate the "net demand" that is load minus PV. If the net demand is less than 0, this considered to be the excess PV generation, which is the power goes to the grid. 
				Hence, the Basecase here is the summation of absolute value of negative net demands for an entire year excluding positive net demands.
			</dd>
			<br>
			<dt>
				"Utilized PV by Battery" based on its definition would be what our battery uses to charge its SOC, correct? How is it calculated?
			</dt>
			<dd>
				Yes this is the amount of energy the battery charges to utilize the excess PV locally.
				"Utilized PV by Battery", in other words, "Feed-in-power reduction" is Basecase value minus EMS value where each of them are calculated as follows:
				The summation absolute value of negative net demands is the Basecase whereas the summation of negative grid energies is the energy to the grid with EMS.
				Again, the net demand is load minus PV and grid energy is net demand – battery charge.				
			</dd>
			<br>
			<dt>
				"Annual Battery Throughput" is supposed to be a cumulative of both battery energy charge and discharge. 
			</dt>
			<dd>
				Yes. It is not only for PV utilization but also for demand charge reduction.
			</dd>
			<br>
			<dt>
				How can I create annual summary of a simulation with PDF format?
			</dt>
			<dd>
				Please select an EMS result from the dropdown menu in Output page, and then click "Generate Annual Report" button.
				Once you click the button, a new tab will be created with its annual report content.
				Please wait for 5-10 seconds for the report to be filled until you see the 12-month summary with the graphs.
				To print this out, just right click and select "print".
				If you are using Google Chrome and want to save as a PDF, change "Destination" from your printer to "Save as PDF".
				You will be able to see the 14 pages of the demand charge minimization report.
			</dd>
		</dl>
	</div>

   <footer>
      <br/>
      <div class="footer">
         <h5>
            <img style="vertical-align:middle"src="../image/NECLA_logo.jpg" alt="NEC Labs Logo"  height="72" />
            <span><a href="http://www.nec-labs.com/research-departments/energy-management/energy-management-home">Energy Management Department, NEC Labs America</a> </span>
         </h5>
      </div>
   </footer>
    
</body>


<style>
#myProgress {
  width: 90%;
  background-color: #ddd;
}

#myBar {
  width: 0%;
  height: 30px;
  background-color: #4CAF50;
  text-align: center;
  line-height: 30px;
  color: white;
}

.batt-config-list {
	width: 180px;
	display: inline-block;
}
.load-config-list {
	width: 240px;
	display: inline-block;
}
.tariff-config-list {
	width: 250px;
	display: inline-block;
}

.tariff-label {
	position: relative;
	display: block;
	*zoom:1;
	padding: 3px 5px;
	margin-bottom: 5px;
}

.delete-tariff-config {
	background: #ccc;
	color: black;
	display: none;
	position:inline;
	margin-left: 10px;
	padding: 1px 4px;
	margin-top: -10px;
	font-size: 12px;
	display:none;
}
.tariff-label:hover .delete-tariff-config {
	display:inline;
}


.delete-load-config {
	background: #ccc;
	color: black;
	display: none;
	position:inline;
	margin-left: 10px;
	padding: 1px 4px;
	margin-top: -10px;
	font-size: 12px;
	display:none;
}
.load-label:hover .delete-load-config {
	display:inline;
}
.delete-load-config:hover {
	cursor: pointer;
	background: red;
	color: white;
}

.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 7px 16px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 13px;
    margin: 3px 1px;
    cursor: pointer;
}

.button2 {background-color: #008CBA;} /* Blue */
.button3 {background-color: #f44336;} /* Red */ 
.button4 {background-color: #e7e7e7; color: black;} /* Gray */ 
.button5 {background-color: #555555;} /* Black */

#parentTab {
    background-color: rgba(255,255,255, 0.95);
}

dt::before {
    content: "Question: ";
} 
dd::before {
    content: "Answer: ";
}
</style>

</html>

